# docker-compose.yml
version: "3.8"
services:
  db:
    image: postgres:15
    container_name: go_app_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST:-db} # defaults to service name if not set
      POSTGRES_PORT: ${DB_PORT:-5432} # defaults to 5432 if not set
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: go_app
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #   environment:
  #     DB_HOST: ${DB_HOST:-db}
  #     DB_PORT: ${DB_PORT:-5432}
  #     DB_USER: ${DB_USER}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     DB_NAME: ${DB_NAME}
volumes:
  db_data:
